### ISSUE TITLE
Precise Maneuver is still available when contact to probe is limited

### ISSUE THREAD

**Issue by chris42** [radistmorse/KSPPreciseManeuver#24]
If you have limited control of the probe, precise maneuver is still available and configurable. As you can still use the maneuver target and full throttle, you can pretty much fly a probe with the maneuver node created. After using the node just update the node and reuse it.
This renders the difficulty setting useless. IMHO precise maneuver should follow the stock availability of the maneuver nodes.

I use this on 1.9.1 and otherwise works without issues, might be a possibility to update the CKAN entries?

**Comment by radistmorse** [comment]
This is a mod. By design this is something that the developers didn't intend in the base game. Of course this changes the game difficulty. I do not plan to include any artificial blockers. For one, there might be too many of them. You think that the mod should be disabled if the probe has limited control, and some may argue that the mod should be disabled if there is no level-2 pilot on board or something like that. You can't predict all. And more importantly, you don't need to. Nobody forces you to use the GUI if you think you are not supposed to. Just switch it off. Why do you want this to be disabled in the code? The game is a sandbox. You make your own challenges.
