### ISSUE TITLE
crash when clicking Apoapsis button to set maneuver location

### ISSUE THREAD

**Issue by ghost** [radistmorse/KSPPreciseManeuver#3]
[error.log.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/233023/error.log.txt)
[output_log.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/233024/output_log.txt)
[crash.dmp.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/233025/crash.dmp.txt)

**Comment by radistmorse** [comment]
Well, first of all, I see some exceptions from KER. This may be the part of the cause, because all the crashes I see always happen in the setups with KER.

But other than that... I'm in a loss. I'm starting to think about introducing a deliberate error to the maneuver time so that it's not placed precisely at AP.

**Comment by ghost** [comment]
Here's a log with just PM installed.  It took me 3 tries of clicking Ap, delete, Ap, delete, then Ap and it crashed.

Hope it helps.

[error.log.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/233528/error.log.txt)
[output_log.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/233529/output_log.txt)
[crash.dmp.txt](https://github.com/radistmorse/KSPPreciseManeuver/files/233530/crash.dmp.txt)

**Comment by ghost** [comment]
I haven't had a single crash since 1.1.2 was released

**Comment by radistmorse** [comment]
Let's hope it'll never strike again.
